// Generated from Givrex Products.dc.html — Givrex catalogue data
export const PRODUCTS = [
  {
    "slug": "okra-special",
    "catFr": "Légumes surgelés",
    "nameFr": "Gombo Special",
    "noteFr": "Pelé en cône, de 1 à 2,5 cm, paré manuellement un par un et non coupé, afin que le gombo garde sa fraîcheur et ses nutriments. Sans filaments ni grosses graines.",
    "tagFr": "IQF",
    "catId": "vegetables",
    "cat": "Frozen Vegetables",
    "catAr": "خضروات مجمّدة",
    "name": "Okra Special",
    "nameAr": "بامية مخصوص",
    "note": "Conically peeled, 1 to 2.5 cm, individually manually trimmed one by one and not cut, so the okra keeps its freshness and nutrients. Free of any filaments or large seeds.",
    "noteAr": "مفروزة بالحجم، كاملة أو مقطّعة. عبوة ٤٠٠ جرام للتجزئة وعبوات كبيرة.",
    "tag": "IQF",
    "tagAr": "تجميد سريع",
    "img": "pack-okra"
  },
  {
    "slug": "minced-molokhia",
    "catFr": "Légumes surgelés",
    "nameFr": "Molokhia",
    "noteFr": "Un légume égyptien naturellement riche en fer, aux feuilles vert foncé. Les feuilles sont traitées de façon particulière pour préserver le haut niveau de douceur qui caractérise ce produit.",
    "tagFr": "IQF",
    "catId": "vegetables",
    "cat": "Frozen Vegetables",
    "catAr": "خضروات مجمّدة",
    "name": "Molokhia",
    "nameAr": "ملوخية مخروطة",
    "note": "An Egyptian vegetable naturally rich in iron, with dark green leaves. The leaves are treated in a particular way to preserve the high level of sweetness that characterizes this product.",
    "noteAr": "مفرومة ناعمة، في قوالب أو سائبة. عبوة ٤٠٠ جرام للتجزئة وعبوات كبيرة.",
    "tag": "IQF",
    "tagAr": "تجميد سريع",
    "img": "pack-molokhia"
  },
  {
    "slug": "mixed-vegetables",
    "catFr": "Légumes surgelés",
    "nameFr": "Macédoine de légumes",
    "noteFr": "Ingrédients : carottes, petits pois et haricots verts. Chacun est soigneusement trié, lavé, coupé puis immédiatement transformé et surgelé pour préserver toutes ses qualités nutritives et gustatives.",
    "tagFr": "IQF",
    "catId": "vegetables",
    "cat": "Frozen Vegetables",
    "catAr": "خضروات مجمّدة",
    "name": "Mixed Vegetables",
    "nameAr": "خضار مشكّل",
    "note": "Ingredients: carrots, green peas and green beans. Each is carefully sorted, washed, cut and then immediately processed and frozen to preserve all natural nutritive and taste characteristics.",
    "noteAr": "بسلة وجزر وفاصوليا خضراء بقطع متوازن. عبوة ٤٠٠ جرام للتجزئة وعبوات كبيرة.",
    "tag": "IQF",
    "tagAr": "تجميد سريع",
    "img": "pack-mixed-vegetables"
  },
  {
    "slug": "artichoke-bottoms",
    "catFr": "Légumes surgelés",
    "nameFr": "Fonds d'artichauts",
    "noteFr": "Artichauts égyptiens sélectionnés de qualité AAA, proposés en calibres de 3 à 5 cm, 5 à 7 cm et 7 à 9 cm.",
    "tagFr": "IQF",
    "catId": "vegetables",
    "cat": "Frozen Vegetables",
    "catAr": "خضروات مجمّدة",
    "name": "Artichoke Bottoms",
    "nameAr": "قواعد خرشوف",
    "note": "Premium selected Egyptian artichokes of AAA quality, supplied in 3 to 5 cm, 5 to 7 cm and 7 to 9 cm calibres.",
    "noteAr": "قواعد منظّفة ومفروزة. عبوة ٤٠٠ جرام للتجزئة وعبوات كبيرة.",
    "tag": "IQF",
    "tagAr": "تجميد سريع",
    "img": "p-artichoke"
  },
  {
    "slug": "green-peas",
    "catFr": "Légumes surgelés",
    "nameFr": "Petits pois",
    "noteFr": "Reçus frais et de premier choix. Un tri minutieux élimine l'amidon et les pois jaunes pour garantir le meilleur produit.",
    "tagFr": "IQF",
    "catId": "vegetables",
    "cat": "Frozen Vegetables",
    "catAr": "خضروات مجمّدة",
    "name": "Green Peas",
    "nameAr": "بسلة",
    "note": "Received fresh and of first choice. A careful sorting process removes the starch and yellow peas to ensure the best product.",
    "noteAr": "بسلة طرية مفروزة بالحجم. عبوة ٤٠٠ جرام للتجزئة وعبوات كبيرة.",
    "tag": "IQF",
    "tagAr": "تجميد سريع",
    "img": "p-peas"
  },
  {
    "slug": "broccoli-florets",
    "catFr": "Légumes surgelés",
    "nameFr": "Brocoli",
    "noteFr": "Composé des meilleures variétés de brocoli. Les fleurettes sont parées manuellement dans notre usine, lavées, blanchies et immédiatement surgelées pour préserver toutes leurs qualités nutritives et gustatives.",
    "tagFr": "IQF",
    "catId": "vegetables",
    "cat": "Frozen Vegetables",
    "catAr": "خضروات مجمّدة",
    "name": "Broccoli",
    "nameAr": "زهرة بروكلي",
    "note": "Composed of the best broccoli varieties. The flowers are manually trimmed in our factory, washed, blanched and immediately frozen to preserve all their natural nutritive and taste characteristics.",
    "noteAr": "زهرات مقطّعة ومسلوقة. عبوة ٤٠٠ جرام للتجزئة وعبوات كبيرة.",
    "tag": "IQF",
    "tagAr": "تجميد سريع",
    "img": "p-broccoli"
  },
  {
    "slug": "cauliflower-florets",
    "catFr": "Légumes surgelés",
    "nameFr": "Chou-fleur",
    "noteFr": "Composé des meilleures variétés de chou-fleur et reconnu pour sa couleur blanche. Les petites fleurettes sont lavées, blanchies et immédiatement surgelées.",
    "tagFr": "IQF",
    "catId": "vegetables",
    "cat": "Frozen Vegetables",
    "catAr": "خضروات مجمّدة",
    "name": "Cauliflower",
    "nameAr": "زهرة قرنبيط",
    "note": "Composed of the best cauliflower varieties and known for its white colour. The small flowers are washed, blanched and immediately frozen.",
    "noteAr": "زهرات مقطّعة ومسلوقة. عبوة ٤٠٠ جرام للتجزئة وعبوات كبيرة.",
    "tag": "IQF",
    "tagAr": "تجميد سريع",
    "img": "p-cauliflower"
  },
  {
    "slug": "sweet-corn",
    "catFr": "Légumes surgelés",
    "nameFr": "Maïs doux en épi",
    "noteFr": "Notre maïs doux est très sucré. Le maïs arrive à l'usine à parfaite maturité, puis il est épluché, blanchi et immédiatement surgelé.",
    "tagFr": "IQF",
    "catId": "vegetables",
    "cat": "Frozen Vegetables",
    "catAr": "خضروات مجمّدة",
    "name": "Sweet Corn on the Cob",
    "nameAr": "ذرة حلوة",
    "note": "Our sweet corn is super sweet. The corn reaches the factory in its perfect mature state, then it is peeled, blanched and immediately frozen.",
    "noteAr": "حبوب مفصولة من الكوز. عبوة ٤٠٠ جرام للتجزئة وعبوات كبيرة.",
    "tag": "IQF",
    "tagAr": "تجميد سريع",
    "img": "p-sweet-corn"
  },
  {
    "slug": "sweet-potatoes",
    "catFr": "Légumes surgelés",
    "nameFr": "Patates douces",
    "noteFr": "Récoltées dans les terres fertiles de la vallée du Nil, riches en limon et en gravier, ce qui donne des tubercules uniformes, beaux et non tordus. Disponibles en dés ou en tranches.",
    "tagFr": "IQF",
    "catId": "vegetables",
    "cat": "Frozen Vegetables",
    "catAr": "خضروات مجمّدة",
    "name": "Sweet Potatoes",
    "nameAr": "بطاطا حلوة",
    "note": "Harvested in the fertile land of the Nile valley, rich in silt and gravel, which gives uniform beautiful tubers untwisted. Available in dices or sliced.",
    "noteAr": "مقشّرة ومقطّعة مكعبات. عبوة ٤٠٠ جرام للتجزئة وعبوات كبيرة.",
    "tag": "IQF",
    "tagAr": "تجميد سريع",
    "img": "p-sweet-potatoes"
  },
  {
    "slug": "gourmet-turned-vegetables",
    "catFr": "Légumes surgelés",
    "nameFr": "Delicatessen",
    "noteFr": "Une gamme delicatessen innovante : légumes tournés de carotte, courgette et pomme de terre, carpaccio d'artichaut et de tomate, légumes pour couscous et légumes julienne.",
    "tagFr": "IQF",
    "catId": "vegetables",
    "cat": "Frozen Vegetables",
    "catAr": "خضروات مجمّدة",
    "name": "Delicatessen",
    "nameAr": "خضار مقشّر بشكل مميز",
    "note": "Innovative delicatessen including vegetables tournés of carrot, zucchini and potato, carpaccio artichokes and tomatoes, mixed vegetables for couscous and julienne vegetables.",
    "noteAr": "جزر وكوسة وبطاطس مخروطة يدويًا. عبوة ٤٠٠ جرام للتجزئة وعبوات كبيرة.",
    "tag": "IQF",
    "tagAr": "تجميد سريع",
    "img": "p-turned-vegetables"
  },
  {
    "slug": "grilled-eggplant",
    "catFr": "Légumes surgelés",
    "nameFr": "Aubergines grillées",
    "noteFr": "Des aubergines fraîches, foncées et brillantes sont lavées, tranchées en épaisseur uniforme et grillées afin d'obtenir des marques de gril visibles sur chaque tranche, puis surgelées.",
    "tagFr": "IQF",
    "catId": "vegetables",
    "cat": "Frozen Vegetables",
    "catAr": "خضروات مجمّدة",
    "name": "Grilled Eggplants",
    "nameAr": "باذنجان مشوي",
    "note": "Fresh dark and shiny eggplants are washed, sliced in a uniform thickness and grilled to obtain visible grill marks on each slice, then frozen.",
    "noteAr": "شرائح مشوية على الفحم. عبوة ٤٠٠ جرام للتجزئة وعبوات كبيرة.",
    "tag": "IQF",
    "tagAr": "تجميد سريع",
    "img": "p-eggplant"
  },
  {
    "slug": "chopped-spinach",
    "catFr": "Légumes surgelés",
    "nameFr": "Épinards",
    "noteFr": "Reçus frais avec leurs feuilles vertes après la cueillette, puis soigneusement triés. La coupe préserve le goût naturel et les qualités nutritives, et un second tri garantit un produit 100 % propre.",
    "tagFr": "IQF",
    "catId": "vegetables",
    "cat": "Frozen Vegetables",
    "catAr": "خضروات مجمّدة",
    "name": "Spinach",
    "nameAr": "سبانخ مفرومة",
    "note": "Received fresh with its green leaves after picking, then carefully sorted. The cutting preserves the natural taste and nutritive characteristics, and a second sorting grants a 100% clean product.",
    "noteAr": "ورق مفروم ومسلوق. عبوة ٤٠٠ جرام للتجزئة وعبوات كبيرة.",
    "tag": "IQF",
    "tagAr": "تجميد سريع",
    "img": "p-spinach"
  },
  {
    "slug": "diced-onions",
    "catFr": "Légumes surgelés",
    "nameFr": "Oignon",
    "noteFr": "Oignons blancs ou rouges au parfum puissant, récoltés dans le sol riche de la vallée du Nil. Proposés en dés prêts à cuisiner ou en tranches de 2 à 6 cm d'épaisseur.",
    "tagFr": "IQF",
    "catId": "vegetables",
    "cat": "Frozen Vegetables",
    "catAr": "خضروات مجمّدة",
    "name": "Onion",
    "nameAr": "بصل مفروم",
    "note": "Strong scented white or red onions harvested from the rich soil of the Nile valley. Offered as dices ready to use in cooking, or slices of 2 to 6 cm thickness.",
    "noteAr": "مقشّر ومقطّع مكعبات. عبوة ٤٠٠ جرام للتجزئة وعبوات كبيرة.",
    "tag": "IQF",
    "tagAr": "تجميد سريع",
    "img": "p-onions"
  },
  {
    "slug": "artichoke-hearts",
    "catFr": "Légumes surgelés",
    "nameFr": "Cœurs d'artichauts",
    "noteFr": "Issus d'une petite variété tendre connue en Égypte sous le nom d'artichaut français ou « Petite Violette ». Nettoyés à l'intérieur pour le farcissage, uniques en leur genre.",
    "tagFr": "IQF",
    "catId": "vegetables",
    "cat": "Frozen Vegetables",
    "catAr": "خضروات مجمّدة",
    "name": "Artichoke Hearts",
    "nameAr": "قلوب الخرشوف",
    "note": "Processed from a small tender variety known in Egypt as the French Artichoke or \u201cPetite Violette\u201d. Cleaned from inside for stuffing, unique in its kind.",
    "noteAr": "قلوب كاملة منظّفة، أحد عشرة أصناف مصنّعة. عبوة ٤٠٠ جرام للتجزئة وعبوات كبيرة.",
    "tag": "IQF",
    "tagAr": "تجميد سريع",
    "img": "p-artichoke-hearts"
  },
  {
    "slug": "peeled-fava-beans",
    "catFr": "Légumes surgelés",
    "nameFr": "Fèves épluchées",
    "noteFr": "L'Égypte est un grand producteur de fèves et Givrex en exporte des centaines de tonnes chaque année. Proposées épluchées (sans peau) ou non épluchées (avec peau).",
    "tagFr": "IQF",
    "catId": "vegetables",
    "cat": "Frozen Vegetables",
    "catAr": "خضروات مجمّدة",
    "name": "Peeled Broad Beans",
    "nameAr": "فول مقشّر",
    "note": "Egypt is a large producer of broad beans and hundreds of tons are exported by Givrex every year. Supplied peeled (skinless) or non peeled (with skin).",
    "noteAr": "يُقشَّر ويُفرز قبل التجميد. عبوة ٤٠٠ جرام للتجزئة وعبوات كبيرة.",
    "tag": "IQF",
    "tagAr": "تجميد سريع",
    "img": "p-fava"
  },
  {
    "slug": "cut-green-beans",
    "catFr": "Légumes surgelés",
    "nameFr": "Haricots verts",
    "noteFr": "À leur arrivée chez Givrex, les haricots doivent être tendres et parfaitement ronds sur toute leur longueur, sans filaments, parasites ni dégâts d'insectes. Entiers ou coupés.",
    "tagFr": "IQF",
    "catId": "vegetables",
    "cat": "Frozen Vegetables",
    "catAr": "خضروات مجمّدة",
    "name": "Green Beans",
    "nameAr": "فاصوليا خضراء مقطعة",
    "note": "When this product reaches Givrex it must be tender and completely rounded over its entire length, free of any filaments, parasites or insect damage. Whole or cut.",
    "noteAr": "مقطّعة ومسلوقة. عبوة ٤٠٠ جرام للتجزئة وعبوات كبيرة.",
    "tag": "IQF",
    "tagAr": "تجميد سريع",
    "img": "p-green-beans"
  },
  {
    "slug": "peeled-and-cut-taro",
    "catFr": "Légumes surgelés",
    "nameFr": "Taro / Colocase",
    "noteFr": "De taille moyenne pour une qualité optimale. La coupe est mécanique et le lavage soigneusement réalisé pour ne pas altérer le goût. Le sachet contient d'autres verdures assorties finement hachées pour faciliter la cuisson.",
    "tagFr": "IQF",
    "catId": "vegetables",
    "cat": "Frozen Vegetables",
    "catAr": "خضروات مجمّدة",
    "name": "Taro / Colocasia",
    "nameAr": "قلقاس مقشر ومقطع",
    "note": "Of medium size for optimal quality. The cutting is carried out mechanically and the washing carefully done to avoid affecting the taste. The bag includes other assorted greenery carefully chopped to make cooking easier.",
    "noteAr": "مقشّر ومقطّع وجاهز للطهي. عبوة ٤٠٠ جرام للتجزئة وعبوات كبيرة.",
    "tag": "IQF",
    "tagAr": "تجميد سريع",
    "img": "p-taro"
  },
  {
    "slug": "artichoke-quarters",
    "catFr": "Légumes surgelés",
    "nameFr": "Artichauts en moitiés et quartiers",
    "noteFr": "Artichauts égyptiens sélectionnés de qualité AAA, coupés en moitiés et en quartiers pour la cuisine et les plats préparés.",
    "tagFr": "IQF",
    "catId": "vegetables",
    "cat": "Frozen Vegetables",
    "catAr": "خضروات مجمّدة",
    "name": "Artichokes in Halves and Quarters",
    "nameAr": "خرشوف أرباع",
    "note": "Premium selected Egyptian artichokes of AAA quality, cut in halves and quarters for cooking and ready meals.",
    "noteAr": "قلوب منظّفة مقطّعة إلى أرباع. عبوة ٤٠٠ جرام للتجزئة وعبوات كبيرة.",
    "tag": "IQF",
    "tagAr": "تجميد سريع",
    "img": "p-artichoke-quarters"
  },
  {
    "slug": "artichoke-cuts",
    "catFr": "Légumes surgelés",
    "nameFr": "Artichauts en tranches, dés et triangles",
    "noteFr": "Tranches et triangles pour pizzas et salades, dés pour garnitures et dips, tous issus d'artichauts égyptiens sélectionnés.",
    "tagFr": "IQF",
    "catId": "vegetables",
    "cat": "Frozen Vegetables",
    "catAr": "خضروات مجمّدة",
    "name": "Artichoke Slices, Dices and Triangles",
    "nameAr": "أصناف الخرشوف",
    "note": "Slices and triangles for pizzas and salads, dices for topping or dipping, all from premium selected Egyptian artichokes.",
    "noteAr": "أنصاف وأرباع ومكعبات ومثلثات حسب المواصفة.",
    "tag": "IQF",
    "tagAr": "تجميد سريع",
    "img": null
  },
  {
    "slug": "strawberries",
    "catFr": "Fruits surgelés",
    "nameFr": "Fraises",
    "noteFr": "Fraises entièrement rouges à brix élevé, mûres et rouges à l'intérieur comme à l'extérieur, d'un haut niveau de sucrosité et sans pesticides. Entières calibrées, coupées ou en moitiés.",
    "tagFr": "IQF",
    "catId": "fruits",
    "cat": "Frozen Fruits",
    "catAr": "فواكه مجمّدة",
    "name": "Strawberries",
    "nameAr": "فراولة",
    "note": "Fully red strawberries with higher brix, ripe and red inside and outside, containing a high level of sweetness and free from pesticides. Whole calibrated, cut and in halves.",
    "noteAr": "عالية البركس، كاملة أو مقطّعة أو مكعبات. عبوة ٤٠٠ جرام للتجزئة وعبوات كبيرة.",
    "tag": "IQF",
    "tagAr": "تجميد سريع",
    "img": "pack-strawberries"
  },
  {
    "slug": "apricots-earlet",
    "catFr": "Fruits surgelés",
    "nameFr": "Abricot",
    "noteFr": "Variété Canino, cultivée sous le soleil égyptien et soigneusement sélectionnée. Issue de fruits frais triés dont les noyaux sont soigneusement retirés, avec une sucrosité plus élevée après surgélation.",
    "tagFr": "IQF",
    "catId": "fruits",
    "cat": "Frozen Fruits",
    "catAr": "فواكه مجمّدة",
    "name": "Apricot",
    "nameAr": "مشمش إيرليت",
    "note": "Canino variety, grown under the Egyptian sun and carefully selected. Derived from fresh fruits sorted with the seeds carefully removed, with a higher sweetness after freezing.",
    "noteAr": "أنصاف منزوعة النوى. عبوة ٤٠٠ جرام للتجزئة وعبوات كبيرة.",
    "tag": "IQF",
    "tagAr": "تجميد سريع",
    "img": "p-apricot"
  },
  {
    "slug": "pomegranate-arils",
    "catFr": "Fruits surgelés",
    "nameFr": "Grains de grenade",
    "noteFr": "Sélectionnés pour leur couleur rouge foncé et leur brix élevé, qui donnent un goût plus sucré. À utiliser en jus, en smoothies ou pour garnir vos plats.",
    "tagFr": "IQF",
    "catId": "fruits",
    "cat": "Frozen Fruits",
    "catAr": "فواكه مجمّدة",
    "name": "Pomegranate Arils",
    "nameAr": "حبّ الرمان",
    "note": "Selected for darker red colour and higher brix, which gives a sweeter taste. Can be used to make juices, smoothies or to garnish various dishes.",
    "noteAr": "حبوب مفصولة يدويًا. عبوة ٤٠٠ جرام للتجزئة وعبوات كبيرة.",
    "tag": "IQF",
    "tagAr": "تجميد سريع",
    "img": "p-pomegranate"
  },
  {
    "slug": "red-figs",
    "catFr": "Fruits surgelés",
    "nameFr": "Figues rouges",
    "noteFr": "Préparées à partir de figues fraîches, lavées et coupées en quartiers dans le sens de la longueur. Cultivées sous le soleil égyptien, récoltées à maturité puis triées à la main.",
    "tagFr": "IQF",
    "catId": "fruits",
    "cat": "Frozen Fruits",
    "catAr": "فواكه مجمّدة",
    "name": "Red Figs",
    "nameAr": "تين أحمر",
    "note": "Prepared using fresh figs, washed and cut in quarters along the length of the fruit. Grown under the Egyptian sun, harvested when ripe, then selected by hand.",
    "noteAr": "تين أحمر كامل وأنصاف. عبوة ٤٠٠ جرام للتجزئة وعبوات كبيرة.",
    "tag": "IQF",
    "tagAr": "تجميد سريع",
    "img": "p-red-figs"
  },
  {
    "slug": "guava",
    "catFr": "Fruits surgelés",
    "nameFr": "Goyave",
    "noteFr": "Un fruit au goût et à la douceur particuliers, très apprécié dans les zones tropicales. Présentée en fruit entier, coupée sur demande ou en pulpe.",
    "tagFr": "IQF",
    "catId": "fruits",
    "cat": "Frozen Fruits",
    "catAr": "فواكه مجمّدة",
    "name": "Guava",
    "nameAr": "جوافة",
    "note": "A fruit with special taste and sweetness, well appreciated by people of tropical zones. Presented as whole fruit, cut upon request or pulp.",
    "noteAr": "أنصاف وقطع جوافة. عبوة ٤٠٠ جرام للتجزئة وعبوات كبيرة.",
    "tag": "IQF",
    "tagAr": "تجميد سريع",
    "img": "p-guava"
  },
  {
    "slug": "mango",
    "catFr": "Fruits surgelés",
    "nameFr": "Mangue",
    "noteFr": "Un fruit au goût et à la douceur particuliers, très apprécié dans les zones tropicales. Présentée en fruit entier, coupée sur demande ou en pulpe.",
    "tagFr": "IQF",
    "catId": "fruits",
    "cat": "Frozen Fruits",
    "catAr": "فواكه مجمّدة",
    "name": "Mango",
    "nameAr": "مانجو",
    "note": "A fruit with a special taste and sweetness, well appreciated by people of tropical zones. Presented as whole fruit, cut upon request or pulp.",
    "noteAr": "مانجو كاملة وشرائح. عبوة ٤٠٠ جرام للتجزئة وعبوات كبيرة.",
    "tag": "IQF",
    "tagAr": "تجميد سريع",
    "img": "p-mango"
  },
  {
    "slug": "dates-zaghloul",
    "catFr": "Fruits surgelés",
    "nameFr": "Dattes Zaghloul",
    "noteFr": "Les dattes Zaghloul sont propres à l'Égypte et à ses palmiers. Elles ont un goût très particulier et noircissent en gagnant en sucrosité après surgélation.",
    "tagFr": "Surgelé",
    "catId": "fruits",
    "cat": "Frozen Fruits",
    "catAr": "فواكه مجمّدة",
    "name": "Zaghloul Dates",
    "nameAr": "بلح زغلول",
    "note": "Zaghloul dates are unique to Egypt and its palms. They have a very particular taste and turn to black with a higher sweetness after freezing.",
    "noteAr": "بلح زغلول أحمر كامل. عبوة ٤٠٠ جرام للتجزئة وعبوات كبيرة.",
    "tag": "Frozen",
    "tagAr": "مجمّد",
    "img": "p-dates-zaghloul"
  },
  {
    "slug": "dates-samani",
    "catFr": "Fruits surgelés",
    "nameFr": "Dattes Samani",
    "noteFr": "L'Égypte est un producteur et exportateur réputé de nombreuses variétés de dattes. Nos dattes surgelées conservent plus longtemps leur douceur et leur texture.",
    "tagFr": "Surgelé",
    "catId": "fruits",
    "cat": "Frozen Fruits",
    "catAr": "فواكه مجمّدة",
    "name": "Samani Dates",
    "nameAr": "بلح سماني",
    "note": "Egypt is a renowned producer and exporter of various varieties of dates. Our frozen dates retain their sweetness and texture for longer.",
    "noteAr": "بلح سماني أصفر كامل. عبوة ٤٠٠ جرام للتجزئة وعبوات كبيرة.",
    "tag": "Frozen",
    "tagAr": "مجمّد",
    "img": "p-dates-samani"
  },
  {
    "slug": "mango-pulp",
    "catFr": "Fruits surgelés",
    "nameFr": "Pulpe de mangue",
    "noteFr": "La pulpe de mangues égyptiennes soigneusement sélectionnées. Poids net 400 g.",
    "tagFr": "Pulpe surgelée",
    "catId": "fruits",
    "cat": "Frozen Fruits",
    "catAr": "فواكه مجمّدة",
    "name": "Mango Pulp",
    "nameAr": "لبّ مانجو",
    "note": "The pulp of carefully selected Egyptian mangoes. Net weight 400 g.",
    "noteAr": "لصناعات العصائر والألبان والحلويات. عبوة ٤٠٠ جرام للتجزئة وعبوات كبيرة.",
    "tag": "Frozen pulp",
    "tagAr": "لبّ مجمّد",
    "img": "p-mango-pulp"
  },
  {
    "slug": "guava-pulp",
    "catFr": "Fruits surgelés",
    "nameFr": "Pulpe de goyave",
    "noteFr": "La pulpe de goyaves égyptiennes soigneusement sélectionnées. Poids net 400 g.",
    "tagFr": "Pulpe surgelée",
    "catId": "fruits",
    "cat": "Frozen Fruits",
    "catAr": "فواكه مجمّدة",
    "name": "Guava Pulp",
    "nameAr": "لبّ جوافة",
    "note": "The pulp of carefully selected Egyptian guavas. Net weight 400 g.",
    "noteAr": "لصناعات العصائر والألبان والحلويات. عبوة ٤٠٠ جرام للتجزئة وعبوات كبيرة.",
    "tag": "Frozen pulp",
    "tagAr": "لبّ مجمّد",
    "img": "p-guava-pulp"
  },
  {
    "slug": "artichoke-cream-soup",
    "catFr": "Soupes prêtes à consommer",
    "nameFr": "Crème d'artichaut",
    "noteFr": "Une crème très nutritive, assemblée et cuisinée pour satisfaire les palais les plus exigeants. Ingrédients : pulpe d'artichaut, farine, beurre frais, sel et lait.",
    "tagFr": "Prêt à consommer",
    "catId": "soups",
    "cat": "Ready to Eat Soups",
    "catAr": "شوربات جاهزة للتناول",
    "name": "Artichoke Cream",
    "nameAr": "شوربة كريمة الخرشوف",
    "note": "A highly nutritious creamy soup, assembled and cooked so as to be worthy of the most discerning palate. Ingredients: artichoke pulp, flour, fresh butter, salt and milk.",
    "noteAr": "محضّرة ومجمّدة وجاهزة للتسخين.",
    "tag": "Ready to eat",
    "tagAr": "جاهزة للتناول",
    "img": null
  },
  {
    "slug": "lentil-cream-soup",
    "catFr": "Soupes prêtes à consommer",
    "nameFr": "Crème de lentilles",
    "noteFr": "Ingrédients : lentilles jaunes, carottes, pommes de terre, tomate, ail, beurre frais ou huile de maïs, sel et condiments. Tous soigneusement sélectionnés et préparés.",
    "tagFr": "Prêt à consommer",
    "catId": "soups",
    "cat": "Ready to Eat Soups",
    "catAr": "شوربات جاهزة للتناول",
    "name": "Lentil Cream",
    "nameAr": "شوربة كريمة العدس",
    "note": "Ingredients: yellow lentil, carrots, potatoes, tomato, garlic, fresh butter or corn oil, salt and condiments. All carefully selected and prepared.",
    "noteAr": "محضّرة ومجمّدة وجاهزة للتسخين.",
    "tag": "Ready to eat",
    "tagAr": "جاهزة للتناول",
    "img": null
  },
  {
    "slug": "broccoli-cream-soup",
    "catFr": "Soupes prêtes à consommer",
    "nameFr": "Crème de brocoli",
    "noteFr": "Ingrédients : brocoli, farine, beurre frais, sel et lait. Assemblée et cuisinée pour satisfaire les palais les plus exigeants.",
    "tagFr": "Prêt à consommer",
    "catId": "soups",
    "cat": "Ready to Eat Soups",
    "catAr": "شوربات جاهزة للتناول",
    "name": "Broccoli Cream",
    "nameAr": "شوربة كريمة البروكلي",
    "note": "Ingredients: broccoli, flour, fresh butter, salt and milk. Assembled and cooked so as to be worthy of the most discerning palate.",
    "noteAr": "محضّرة ومجمّدة وجاهزة للتسخين.",
    "tag": "Ready to eat",
    "tagAr": "جاهزة للتناول",
    "img": null
  },
  {
    "slug": "leek-cream-soup",
    "catFr": "Soupes prêtes à consommer",
    "nameFr": "Crème de poireau",
    "noteFr": "L'une des crèmes de soupes Givrex, un plat prêt à réchauffer élaboré à partir d'ingrédients soigneusement sélectionnés et préparés.",
    "tagFr": "Prêt à consommer",
    "catId": "soups",
    "cat": "Ready to Eat Soups",
    "catAr": "شوربات جاهزة للتناول",
    "name": "Leek Cream",
    "nameAr": "شوربة كريمة الكُرّاث",
    "note": "One of the Givrex creams of soups, a heat and eat ready meal made from carefully selected and prepared ingredients.",
    "noteAr": "محضّرة ومجمّدة وجاهزة للتسخين.",
    "tag": "Ready to eat",
    "tagAr": "جاهزة للتناول",
    "img": null
  },
  {
    "slug": "falafel",
    "catFr": "Plats préparés",
    "nameFr": "Falafel semi-frit",
    "noteFr": "Des ingrédients soigneusement sélectionnés, de l'ail, des herbes fraîches et des condiments sont habilement hachés en une pâte homogène, façonnés en galettes uniformes et semi-frits jusqu'à une belle coloration dorée. Prêt à réchauffer et convient à un régime végétalien.",
    "tagFr": "Prêt à cuire",
    "catId": "meals",
    "cat": "Ready Meals",
    "catAr": "أطباق جاهزة",
    "name": "Semi Fried Falafel",
    "nameAr": "طعمية",
    "note": "Carefully selected ingredients, garlic, fresh herbs and condiments are skillfully minced into a homogenous paste, formed into uniform patties and semi-fried until golden brown. Ready to heat and eat, and suitable for a vegan diet.",
    "noteAr": "أقراص مقسّمة، تُقلى أو تُخبز من المجمّد.",
    "tag": "Ready to cook",
    "tagAr": "جاهزة للطهي",
    "img": "pack-falafel"
  },
  {
    "slug": "value-added-items",
    "catFr": "Plats préparés",
    "nameFr": "Pâtes",
    "noteFr": "La pâte à falafel est un mélange de fèves et de légumes soigneusement assaisonné, le plat préféré des végétariens et une garniture idéale pour les sandwichs. La gamme comprend aussi les purées d'artichaut, de pomme de terre et de patate douce.",
    "tagFr": "Sur cahier des charges",
    "catId": "meals",
    "cat": "Ready Meals",
    "catAr": "أطباق جاهزة",
    "name": "Pastes",
    "nameAr": "منتجات ذات قيمة مضافة",
    "note": "The falafel paste is a mixture of broad beans and vegetables carefully seasoned, the vegetarians favourite meal and an ideal filling for sandwiches. The range also includes mashed artichokes, potatoes and sweet potatoes.",
    "noteAr": "خطوط مجمّدة تُطوَّر حسب طلب العميل.",
    "tag": "To specification",
    "tagAr": "حسب المواصفة",
    "img": null
  }
];

export const bySlug = (slug) => PRODUCTS.find(p => p.slug === slug) || PRODUCTS[0];
export const inCategory = (catId, exceptSlug) => PRODUCTS.filter(p => p.catId === catId && p.slug !== exceptSlug);
